/**<!-------------------------------------------------------------------->
   @class  MLTLensSubpathMutation
   @author Travis Fischer (fisch0920@gmail.com)
   @date   Spring 2009
   
   @brief
      Lens Subpath mutations aim to stratify samples over the image plane. 
   Each mutation consists of deleting the lens subpath of the current path 
   and replacing it by a new one (lens subpaths are of the form (L|D)S*E).
   Lens subpaths are stratified across the image plane using a pseudo-random 
   rover pattern generated by DissolveSampleGeneratorThread.
   
   @see p. 354-355 of Veach's thesis (section 11.4.4)
   <!-------------------------------------------------------------------->**/

#ifndef MLT_LENS_SUBPATH_MUTATION_H_
#define MLT_LENS_SUBPATH_MUTATION_H_

#include <renderers/mlt/MLTPathMutation.h>
#include <renderers/generators/generators.h>

namespace milton {

class MILTON_DLL_EXPORT MLTLensSubpathMutation : public MLTPathMutation {
   public:
      ///@name Constructors
      //@{-----------------------------------------------------------------
      
      inline MLTLensSubpathMutation(MLTRenderer *renderer = NULL)
         : MLTPathMutation(renderer), 
           m_generator(NULL), m_noSamples(NULL)
      { }
      
      virtual ~MLTLensSubpathMutation();
      
      
      //@}-----------------------------------------------------------------
      ///@name Initialization
      //@{-----------------------------------------------------------------
      
      virtual void init();
      
      
      //@}-----------------------------------------------------------------
      ///@name Main usage interface
      //@{-----------------------------------------------------------------
      
      virtual real_t mutate(const Path &X, Path &Y);
      
      
      //@}-----------------------------------------------------------------
      
   protected:
      DissolveSampleGeneratorThread *m_generator;
      unsigned *m_noSamples;
      unsigned  m_maxSamples;
      unsigned  m_curSamples;
};

}

#endif // MLT_LENS_SUBPATH_MUTATION_H_

